# Generated by Django 5.1.6 on 2025-03-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_notes', to='hoa_tracking_app.association')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('liability', 'General Liability'), ('property', 'Property Insurance'), ('directors', 'Directors & Officers'), ('umbrella', 'Umbrella Policy'), ('workers_comp', 'Workers Compensation'), ('flood', 'Flood Insurance'), ('other', 'Other')], max_length=20)),
                ('policy_number', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('renewal_reminder_days', models.IntegerField(default=30)),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='insurance_policies/')),
                ('notes', models.TextField(blank=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='hoa_tracking_app.association')),
            ],
        ),
        migrations.CreateModel(
            name='StateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('incorporation', 'Articles of Incorporation'), ('business_license', 'Business License'), ('tax_exempt', 'Tax Exempt Status'), ('annual_report', 'Annual Report'), ('other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(max_length=50)),
                ('issuing_authority', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('renewal_reminder_days', models.IntegerField(default=30)),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='state_registrations/')),
                ('notes', models.TextField(blank=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_registrations', to='hoa_tracking_app.association')),
            ],
        ),
    ]
